In [1]:
import requests
def get_market_data(symbol,tf,limit):
        url = "https://api.binance.com/api/v3/klines"
        params = {
            "symbol": symbol,
            "interval": tf,
            "limit": limit
        }
        try:
            response = requests.get(url, params=params)
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"An error occurred: {e}")
            if e.response is not None:
                print("Response content:", e.response.content)

In [2]:
import pandas as pd
data=get_market_data("ETHBTC", "1d", 1000)
df = pd.DataFrame(data, columns=['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume', 'Close_time', 'Quote_asset_volume', 'Number_of_trades', 'Taker_buy_base', 'Taker_buy_quote', 'Ignore'])

In [3]:
df

,Timestamp,Open,High,Low,Close,Volume,Close_time,Quote_asset_volume,Number_of_trades,Taker_buy_base,Taker_buy_quote,Ignore
0,1663459200000,0.07303200,0.07305700,0.06811700,0.06872100,107924.25440000,1663545599999,7630.77843079,326972,50529.77820000,3572.30969795,0
1,1663545600000,0.06872300,0.07097700,0.06833100,0.07043200,118123.54350000,1663631999999,8263.38637700,479718,60793.89080000,4253.66651936,0
2,1663632000000,0.07043200,0.07175000,0.06967000,0.07009600,94453.50900000,1663718399999,6664.66851558,349851,45201.70990000,3189.69254323,0
3,1663718400000,0.07009400,0.07135100,0.06708500,0.06749300,122550.74450000,1663804799999,8533.55931656,395780,58161.55980000,4052.48922094,0
4,1663804800000,0.06748900,0.06914500,0.06661500,0.06836300,112931.22750000,1663891199999,7645.72900186,298574,56499.01240000,3826.67309088,0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1749427200000,0.02374000,0.02444000,0.02347000,0.02430000,28025.04410000,1749513599999,665.81954134,72884,13377.45500000,318.23601704,0
996,1749513600000,0.02431000,0.02569000,0.02430000,0.02554000,55526.96290000,1749599999999,1386.54866266,168578,29950.68050000,747.95216661,0
997,1749600000000,0.02554000,0.02623000,0.02521000,0.02551000,56954.91740000,1749686399999,1459.89251025,149298,25767.72560000,661.10400331,0
998,1749686400000,0.02551000,0.02574000,0.02475000,0.02502000,31104.72450000,1749772799999,789.28423708,99988,13744.38370000,349.06378290,0
999,1749772800000,0.02501000,0.02503000,0.02390000,0.02410000,19746.51060000,1749859199999,481.78726594,63334,8096.52500000,197.75259393,0

In [6]:
import pandas as pd

df = df.sort_values(by="Timestamp")
df['Timestamp'] = pd.to_datetime(df['Timestamp'],unit='ms')

df['time_idx'] = (df['Timestamp'] - df['Timestamp'].min()).dt.days

In [7]:
df

,Timestamp,Open,High,Low,Close,Volume,Close_time,Quote_asset_volume,Number_of_trades,Taker_buy_base,Taker_buy_quote,Ignore,time_idx
0,2022-09-18,0.07303200,0.07305700,0.06811700,0.06872100,107924.25440000,1663545599999,7630.77843079,326972,50529.77820000,3572.30969795,0,0
1,2022-09-19,0.06872300,0.07097700,0.06833100,0.07043200,118123.54350000,1663631999999,8263.38637700,479718,60793.89080000,4253.66651936,0,1
2,2022-09-20,0.07043200,0.07175000,0.06967000,0.07009600,94453.50900000,1663718399999,6664.66851558,349851,45201.70990000,3189.69254323,0,2
3,2022-09-21,0.07009400,0.07135100,0.06708500,0.06749300,122550.74450000,1663804799999,8533.55931656,395780,58161.55980000,4052.48922094,0,3
4,2022-09-22,0.06748900,0.06914500,0.06661500,0.06836300,112931.22750000,1663891199999,7645.72900186,298574,56499.01240000,3826.67309088,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2025-06-09,0.02374000,0.02444000,0.02347000,0.02430000,28025.04410000,1749513599999,665.81954134,72884,13377.45500000,318.23601704,0,995
996,2025-06-10,0.02431000,0.02569000,0.02430000,0.02554000,55526.96290000,1749599999999,1386.54866266,168578,29950.68050000,747.95216661,0,996
997,2025-06-11,0.02554000,0.02623000,0.02521000,0.02551000,56954.91740000,1749686399999,1459.89251025,149298,25767.72560000,661.10400331,0,997
998,2025-06-12,0.02551000,0.02574000,0.02475000,0.02502000,31104.72450000,1749772799999,789.28423708,99988,13744.38370000,349.06378290,0,998
999,2025-06-13,0.02501000,0.02503000,0.02390000,0.02410000,19746.51060000,1749859199999,481.78726594,63334,8096.52500000,197.75259393,0,999

In [16]:
# Known real inputs: time features
df['day_of_week'] = df['Timestamp'].dt.dayofweek
df['month'] = df['Timestamp'].dt.month
df["group_id"] = "BTCUSDT"

# Lag feature (optional)
df['lag_1'] = df['Close'].shift(1)

In [17]:
from pytorch_forecasting import TimeSeriesDataSet
from pytorch_forecasting.data import NaNLabelEncoder

max_encoder_len = 30  # History length
max_pred_len = 7      # Forecast horizon

training_cutoff = df["time_idx"].max() - max_pred_len

training = TimeSeriesDataSet(
    df[df.time_idx <= training_cutoff],
    time_idx="time_idx",
    target="Close",
    group_ids=["group_id"],
    
    static_categoricals=["group_id"],
    time_varying_known_reals=["time_idx", "day_of_week", "month"],
    time_varying_unknown_reals=["Close"],

    max_encoder_length=max_encoder_len,
    max_prediction_length=max_pred_len,
    target_normalizer=NaNLabelEncoder(),
    add_relative_time_idx=True,
    add_target_scales=True,
    add_encoder_length=True,
)

In [19]:
from torch.utils.data import DataLoader
from pytorch_forecasting import TemporalFusionTransformer
from pytorch_forecasting.metrics import QuantileLoss
from pytorch_lightning import Trainer

# Dataloaders
train_dataloader = training.to_dataloader(train=True, batch_size=64)

from pytorch_forecasting import TemporalFusionTransformer
from pytorch_forecasting.metrics import QuantileLoss
from pytorch_lightning import Trainer

tft = TemporalFusionTransformer.from_dataset(
    training,
    learning_rate=0.03,
    hidden_size=16,
    attention_head_size=1,
    dropout=0.1,
    loss=QuantileLoss(),
    log_interval=10,
    log_val_interval=1,
)

lightning_model = tft.to_lightning_module()

trainer = Trainer(max_epochs=20, gradient_clip_val=0.1)

trainer.fit(lightning_model, train_dataloaders=train_dataloader)

AttributeError: 'TemporalFusionTransformer' object has no attribute 'to_lightning_module'

In [ ]:
# Predict
raw_preds, x = tft.predict(train_dataloader, mode="raw", return_x=True)

# Plot one sample forecast
tft.plot_prediction(x, raw_preds, idx=0)

In [21]:
!pip show pytorch-forecasting
!pip show pytorch-lightning

Name: pytorch-forecasting
Version: 1.3.0
Summary: Forecasting timeseries with PyTorch - dataloaders, normalizers, metrics and models
Home-page:
Author: Jan Beitner
Author-email:
License:
Location: C:\Users\abina\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages
Requires: lightning, numpy, pandas, scikit-learn, scipy, torch
Required-by:
Name: pytorch-lightning
Version: 2.5.1.post0
Summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
Home-page: https://github.com/Lightning-AI/lightning
Author: Lightning AI et al.
Author-email: pytorch@lightning.ai
License: Apache-2.0
Location: C:\Users\abina\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages
Requires: fsspec, lightning-utilities, packaging, PyYAML, torch, torchmetrics, tqdm, typing-extensions
Required-by: lightning